# This is a basic workflow to help you get started with Actions

name: HolaMundo
on:
  push:
    branches: [ "github-action" ]
  pull_request:
    branches: [ "github-action" ]
jobs:
  hola-mundo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Variables
        run: echo "USERNAME=${{ github.actor }}" > $GITHUB_ENV
      - name: Run script
        run: node Github Actions/hola-mundo.js
